---
title: 'Status of the Petrale sole stock in U.S. waters off the coast of U.S. West Coast in 2023'
author:
  - name: 'Vladlena Gertseva'
    affiliations:
      - name: 'NOAA Fisheries Northwest Fisheries Science Center'
        address: '2725 Montlake Boulevard East'
        city: 'Seattle'
        state: 'WA'
        postal-code: '98112-2097'
  - name: 'Ian G. Taylor'
    affiliations:
      - name: 'NOAA Fisheries Northwest Fisheries Science Center'
        address: '2725 Montlake Boulevard East'
        city: 'Seattle'
        state: 'WA'
        postal-code: '98112-2097'
  - name: 'Nick Tolimieri'
    affiliations:
      - name: 'NOAA Fisheries Northwest Fisheries Science Center'
        address: '2725 Montlake Boulevard East'
        city: 'Seattle'
        state: 'WA'
        postal-code: '98112-2097'
date: today
cover: support_files/Petrale_sole.png
format: 
  pdf: 
    documentclass: scrartcl
    number-sections: true
    template-partials:
      - 'support_files/before-body.tex'
      - 'support_files/_titlepage.tex'
    include-in-header:
      - 'support_files/in-header.tex'
    toc: true
    lof: true
    lot: true
    titlepage-geometry: 
      - top=2in
      - bottom=1in
      - right=1in
      - left=1in
params:
   office: 'NWFSC'
   species: 'Petrale sole'
   spp_latin: 'Eopsetta jordani'
   region: 'U.S. West Coast'
   nf: 'North fleet'
   sf: 'South fleet'
---
{{< pagebreak >}} 

Please cite this publication as 

Taylor, I.G., V. Gertseva, N. Tolimieri. 2023. Status of the Petrale sole stock in U.S. waters off the coast of U.S. West Coast in 2023. NOAA Fisheries Science Center, Seattle, WA. 

 {{< pagebreak >}} 

```{r, results='asis'}
#| label: 'executive_summary'
#| eval: true
#| echo: false
#| warning: false
a <- knitr::knit_child('executive_summary.qmd', quiet = TRUE)
cat(a, sep = '\n')
```

 {{< pagebreak >}} 

```{r, results='asis'}
#| label: 'introduction'
#| eval: true
#| echo: false
#| warning: false
a <- knitr::knit_child('introduction.qmd', quiet = TRUE)
cat(a, sep = '\n')
```

 {{< pagebreak >}} 

```{r, results='asis'}
#| label: 'data'
#| eval: true
#| echo: false
#| warning: false
a <- knitr::knit_child('data.qmd', quiet = TRUE)
cat(a, sep = '\n')
```

 {{< pagebreak >}} 

```{r, results='asis'}
#| label: 'modeling_approach'
#| eval: true
#| echo: false
#| warning: false
a <- knitr::knit_child('modeling_approach.qmd', quiet = TRUE)
cat(a, sep = '\n')
```

 {{< pagebreak >}} 

```{r, results='asis'}
#| label: 'results'
#| eval: true
#| echo: false
#| warning: false
a <- knitr::knit_child('results.qmd', quiet = TRUE)
cat(a, sep = '\n')
```

 {{< pagebreak >}} 

```{r, results='asis'}
#| label: 'projections'
#| eval: true
#| echo: false
#| warning: false
a <- knitr::knit_child('projections.qmd', quiet = TRUE)
cat(a, sep = '\n')
```

 {{< pagebreak >}} 

```{r, results='asis'}
#| label: 'discussion'
#| eval: true
#| echo: false
#| warning: false
a <- knitr::knit_child('discussion.qmd', quiet = TRUE)
cat(a, sep = '\n')
```

 {{< pagebreak >}} 

```{r, results='asis'}
#| label: 'acknowlesgements'
#| eval: true
#| echo: false
#| warning: false
a <- knitr::knit_child('acknowledgments.qmd', quiet = TRUE)
cat(a, sep = '\n')
```

 {{< pagebreak >}} 

```{r, results='asis'}
#| label: 'references'
#| eval: true
#| echo: false
#| warning: false
a <- knitr::knit_child('references.qmd', quiet = TRUE)
cat(a, sep = '\n')
```

 {{< pagebreak >}} 

```{r, results='asis'}
#| label: 'tables'
#| eval: false
#| echo: false
#| warning: false
a <- knitr::knit_child('tables.qmd', quiet = TRUE)
cat(a, sep = '\n')
```

 {{< pagebreak >}} 

```{r, results='asis'}
#| label: 'figures'
#| eval: false
#| echo: false
#| warning: false
a <- knitr::knit_child('figures.qmd', quiet = TRUE)
cat(a, sep = '\n')
```

 {{< pagebreak >}} 

```{r, results='asis'}
#| label: 'appendix'
#| eval: true
#| echo: false
#| warning: false
a <- knitr::knit_child('appendix.qmd', quiet = TRUE)
cat(a, sep = '\n')
```
